CREATE TABLE IF NOT EXISTS feedbacks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tipo TEXT NOT NULL,
  tipo_servico TEXT NOT NULL DEFAULT '',
  regiao TEXT NOT NULL,
  unidade TEXT NOT NULL,
  nota INTEGER NOT NULL DEFAULT 0,
  descricao TEXT NOT NULL,
  nome TEXT,
  telefone TEXT,
  email TEXT,
  anonimo INTEGER NOT NULL DEFAULT 0,
  protocolo TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
